environment: production
chdir: /home/www/altburo/current/
address: 127.0.0.1
user: www-data
group: www-data
port: 8000
pid: /home/www/altburo/current/tmp/thin.pid
rackup: /home/www/altburo/current/config.ru
log: /home/www/altburo/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true